name: rrc_test

task_name: custom

# horizon: 4
horizon: 5
n_obs_steps: 1
n_action_steps: 3

shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    point_cloud:
      shape: [2500, 3]
      type: point_cloud
    agent_pos:
      shape: [7]
      type: low_dimx
  action:
    shape: [7]

env_runner: null

dataset:
  _target_: diffusion_policy_3d.dataset.rrc_dataset.RRCDataset
  zarr_path: /scratch/darshil.jariwala/full_frequency_correct.zarr  
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 42
  val_ratio: 0.02
  max_train_episodes: null
