name: xarm6_pick_place

task_name: pick_place

shape_meta: &shape_meta # acceptable types: rgb, low_dim
  obs:
    point_cloud:
      shape: [2500, 3]
      type: point_cloud
    agent_pos:
      shape: [7]
      type: low_dimx
  action:
    shape: [7]

env_runner:
  _target_: diffusion_policy_3d.env_runner.pybullet_runner.XArm6GripperPyBulletRunner
  n_train: 20
  max_steps: 365
  n_obs_steps: ${n_obs_steps}
  n_action_steps: ${n_action_steps}
  fps: 10
  action_dim: ${eval:'${shape_meta.action.shape}[0]'}
  # capture_table: false
  # # task_name: pick_place we don't need this for pybullet env

dataset:
  _target_: diffusion_policy_3d.dataset.rrc_dataset.RRCDataset # same format as droid dataset
  zarr_path: /scratch/darshil.jariwala/dp3_sim_data/xarm6_gripper/rrc_gripper_sim_dataset.zarr
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 42
  val_ratio: 0.02
  max_train_episodes: null
